# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "PROFILE" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"email" VARCHAR NOT NULL,"phone" VARCHAR NOT NULL,"firstName" VARCHAR,"lastName" VARCHAR,"address" VARCHAR,"birthday" BIGINT,"created" BIGINT);
create table "USER" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"username" VARCHAR NOT NULL,"password" VARCHAR NOT NULL,"created" BIGINT NOT NULL);

# --- !Downs

drop table "PROFILE";
drop table "USER";

